name: Voice solution Resiliency test
#on: [push]
on:
  schedule:
    # * is a special character in YAML so you have t quote this string
    - cron:  '30 23 * * 0-4'
jobs:
  build:
    # Job name is Run Resiliency test
    name: Run_Resiliency_test
    # This job runs on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 42000
    strategy:
      matrix:
        environment:
          - dev
        location:
          - eastus2 
      fail-fast: false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@2036a08    
      - uses: ./.engage-actions/setup-genesysengage
      - name: Set Context
        run: |
          kubectl config use-context aks01-eastus2-${{ matrix.environment }}
      - name: Updated west values
      - name: print values
        run: cat /home/runner/work/voice_resiliency_test/voice_resiliency_test/helm/values.yaml
      - name: Resiliency Pod Deployment
        timeout-minutes: 30000
        run: |          
          cd /home/runner/work/voice_resiliency_test/voice_resiliency_test/helm/
          helm install voice-resiliency-test . -n voice --set version="1.0.0"
          helm test voice-resiliency-test -n voice --timeout 500m          
          
      - uses: ./.voice-test/teams-notification
        env:
          result: "Success"
          activity : "Resiliency Regression Automation"
          action: "Test"
          service: "Resiliency-Automation-Pipeline"
          environment: ${{ matrix.environment }}
          location: ${{ matrix.location }}
          author: "asmitha.durairaj@genesys.com"          
          resiliencylog: "<a href='https://portal.azure.com/#blade/Microsoft_Azure_FileStorage/FileShareMenuBlade/overview/storageAccountId/%2Fsubscriptions%2F1649ee20-8f97-4941-be59-cb40e8aaafea%2FresourceGroups%2Fgroup-aks01-eastus2-dev-nodes%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Flogshareeastus2dev/path/logs/protocol/SMB'>RESILIENCY_Log_File_share_path</a> 
      
      - name: Delete helm chart
        if: ${{ always() }}
        run: |
          cd /home/runner/work/voice_resiliency_test/voice_resiliency_test/helm/    
          helm delete voice-resiliency-test -n voice
          
